steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/$PROJECT_ID/apparitions-repo/apparitions-service:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/$PROJECT_ID/apparitions-repo/apparitions-service:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'apparitions-service'
      - '--image'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/apparitions-repo/apparitions-service:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'
      - '--allow-unauthenticated'

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/apparitions-repo/apparitions-service:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
