import { WordData } from './types';

export const COLORS = {
  bg: '#000000',
  white: '#FFFFFF',
  red: '#FF0000',
  redDim: '#880000',
};

export const WORDS: WordData[] = [
  // A0: Basic Objects and People (15 De, 15 Het)
  { word: 'hond', article: 'de', dim: 'hondje', plural: 'honden', level: 0, boss: false, english: 'dog' },
  { word: 'kat', article: 'de', dim: 'katje', plural: 'katten', level: 0, boss: false, english: 'cat' },
  { word: 'auto', article: 'de', dim: 'autootje', plural: "auto's", level: 0, boss: false, english: 'car' },
  { word: 'tafel', article: 'de', dim: 'tafeltje', plural: 'tafels', level: 0, boss: false, english: 'table' },
  { word: 'man', article: 'de', dim: 'mannetje', plural: 'mannen', level: 0, boss: false, english: 'man' },
  { word: 'vrouw', article: 'de', dim: 'vrouwtje', plural: 'vrouwen', level: 0, boss: false, english: 'woman' },
  { word: 'fiets', article: 'de', dim: 'fietsje', plural: 'fietsen', level: 0, boss: false, english: 'bicycle' },
  { word: 'appel', article: 'de', dim: 'appeltje', plural: 'appels', level: 0, boss: false, english: 'apple' },
  { word: 'boom', article: 'de', dim: 'boompje', plural: 'bomen', level: 0, boss: false, english: 'tree' },
  { word: 'deur', article: 'de', dim: 'deurtje', plural: 'deuren', level: 0, boss: false, english: 'door' },
  { word: 'stoel', article: 'de', dim: 'stoeltje', plural: 'stoelen', level: 0, boss: false, english: 'chair' },
  { word: 'melk', article: 'de', dim: 'melkje', plural: 'melken', level: 0, boss: false, english: 'milk' },
  { word: 'krant', article: 'de', dim: 'krantje', plural: 'kranten', level: 0, boss: false, english: 'newspaper' },
  { word: 'zoon', article: 'de', dim: 'zoontje', plural: 'zonen', level: 0, boss: false, english: 'son' },
  { word: 'jas', article: 'de', dim: 'jasje', plural: 'jassen', level: 0, boss: false, english: 'coat' },
  { word: 'huis', article: 'het', dim: 'huisje', plural: 'huizen', level: 0, boss: true, english: 'house' },
  { word: 'boek', article: 'het', dim: 'boekje', plural: 'boeken', level: 0, boss: false, english: 'book' },
  { word: 'kind', article: 'het', dim: 'kindje', plural: 'kinderen', level: 0, boss: true, english: 'child' },
  { word: 'raam', article: 'het', dim: 'raampje', plural: 'ramen', level: 0, boss: false, english: 'window' },
  { word: 'bed', article: 'het', dim: 'bedje', plural: 'bedden', level: 0, boss: false, english: 'bed' },
  { word: 'brood', article: 'het', dim: 'broodje', plural: 'broden', level: 0, boss: false, english: 'bread' },
  { word: 'glas', article: 'het', dim: 'glaasje', plural: 'glazen', level: 0, boss: false, english: 'glass' },
  { word: 'water', article: 'het', dim: 'watertje', plural: 'wateren', level: 0, boss: false, english: 'water' },
  { word: 'meisje', article: 'het', dim: 'meisje', plural: 'meisjes', level: 0, boss: false, english: 'girl' },
  { word: 'paard', article: 'het', dim: 'paardje', plural: 'paarden', level: 0, boss: false, english: 'horse' },
  { word: 'potlood', article: 'het', dim: 'potloodje', plural: 'potloden', level: 0, boss: false, english: 'pencil' },
  { word: 'dier', article: 'het', dim: 'diertje', plural: 'dieren', level: 0, boss: false, english: 'animal' },
  { word: 'schaap', article: 'het', dim: 'schaapje', plural: 'schapen', level: 0, boss: false, english: 'sheep' },
  { word: 'varken', article: 'het', dim: 'varkentje', plural: 'varkens', level: 0, boss: false, english: 'pig' },
  { word: 'ei', article: 'het', dim: 'eitje', plural: 'eieren', level: 0, boss: false, english: 'egg' },

  // A1: Common Surroundings and Daily Life (15 De, 15 Het)
  { word: 'stad', article: 'de', dim: 'stadje', plural: 'steden', level: 1, boss: true, english: 'city' },
  { word: 'school', article: 'de', dim: 'schooltje', plural: 'scholen', level: 1, boss: false, english: 'school' },
  { word: 'dag', article: 'de', dim: 'dagje', plural: 'dagen', level: 1, boss: false, english: 'day' },
  { word: 'tijd', article: 'de', dim: 'tijdje', plural: 'tijden', level: 1, boss: false, english: 'time' },
  { word: 'weg', article: 'de', dim: 'weggetje', plural: 'wegen', level: 1, boss: false, english: 'road' },
  { word: 'vriend', article: 'de', dim: 'vriendje', plural: 'vrienden', level: 1, boss: false, english: 'friend' },
  { word: 'kamer', article: 'de', dim: 'kamertje', plural: 'kamers', level: 1, boss: false, english: 'room' },
  { word: 'vraag', article: 'de', dim: 'vraagje', plural: 'vragen', level: 1, boss: false, english: 'question' },
  { word: 'naam', article: 'de', dim: 'naampje', plural: 'namen', level: 1, boss: false, english: 'name' },
  { word: 'hand', article: 'de', dim: 'handje', plural: 'handen', level: 1, boss: false, english: 'hand' },
  { word: 'voet', article: 'de', dim: 'voetje', plural: 'voeten', level: 1, boss: false, english: 'foot' },
  { word: 'vogel', article: 'de', dim: 'vogeltje', plural: 'vogels', level: 1, boss: false, english: 'bird' },
  { word: 'trein', article: 'de', dim: 'treintje', plural: 'treinen', level: 1, boss: false, english: 'train' },
  { word: 'bus', article: 'de', dim: 'busje', plural: 'bussen', level: 1, boss: false, english: 'bus' },
  { word: 'straat', article: 'de', dim: 'straatje', plural: 'straten', level: 1, boss: false, english: 'street' },
  { word: 'land', article: 'het', dim: 'landje', plural: 'landen', level: 1, boss: false, english: 'country' },
  { word: 'jaar', article: 'het', dim: 'jaartje', plural: 'jaren', level: 1, boss: true, english: 'year' },
  { word: 'werk', article: 'het', dim: 'werkje', plural: 'werken', level: 1, boss: false, english: 'work' },
  { word: 'oog', article: 'het', dim: 'oogje', plural: 'ogen', level: 1, boss: false, english: 'eye' },
  { word: 'geld', article: 'het', dim: 'geldje', plural: 'gelden', level: 1, boss: false, english: 'money' },
  { word: 'station', article: 'het', dim: 'stationnetje', plural: 'stations', level: 1, boss: false, english: 'station' },
  { word: 'vliegtuig', article: 'het', dim: 'vliegtuigje', plural: 'vliegtuigen', level: 1, boss: false, english: 'airplane' },
  { word: 'ziekenhuis', article: 'het', dim: 'ziekenhuisje', plural: 'ziekenhuizen', level: 1, boss: false, english: 'hospital' },
  { word: 'restaurant', article: 'het', dim: 'restaurantje', plural: 'restaurants', level: 1, boss: false, english: 'restaurant' },
  { word: 'strand', article: 'het', dim: 'strandje', plural: 'stranden', level: 1, boss: false, english: 'beach' },
  { word: 'bos', article: 'het', dim: 'bosje', plural: 'bossen', level: 1, boss: false, english: 'forest' },
  { word: 'feest', article: 'het', dim: 'feestje', plural: 'feesten', level: 1, boss: false, english: 'party' },
  { word: 'gesprek', article: 'het', dim: 'gesprekje', plural: 'gesprekken', level: 1, boss: false, english: 'conversation' },
  { word: 'antwoord', article: 'het', dim: 'antwoordje', plural: 'antwoorden', level: 1, boss: false, english: 'answer' },
  { word: 'adres', article: 'het', dim: 'adresje', plural: 'adressen', level: 1, boss: false, english: 'address' },

  // A2: Concepts and Social Interaction (15 De, 15 Het)
  { word: 'kans', article: 'de', dim: 'kansje', plural: 'kansen', level: 2, boss: false, english: 'chance' },
  { word: 'reden', article: 'de', dim: 'redentje', plural: 'redenen', level: 2, boss: false, english: 'reason' },
  { word: 'manier', article: 'de', dim: 'maniertje', plural: 'manieren', level: 2, boss: false, english: 'way' },
  { word: 'wereld', article: 'de', dim: 'wereldje', plural: 'werelden', level: 2, boss: false, english: 'world' },
  { word: 'situatie', article: 'de', dim: 'situatietje', plural: 'situaties', level: 2, boss: false, english: 'situation' },
  { word: 'familie', article: 'de', dim: 'familietje', plural: 'families', level: 2, boss: false, english: 'family' },
  { word: 'markt', article: 'de', dim: 'marktje', plural: 'markten', level: 2, boss: false, english: 'market' },
  { word: 'prijs', article: 'de', dim: 'prijsje', plural: 'prijzen', level: 2, boss: false, english: 'price' },
  { word: 'groep', article: 'de', dim: 'groepje', plural: 'groepen', level: 2, boss: false, english: 'group' },
  { word: 'keuze', article: 'de', dim: 'keuzetje', plural: 'keuzes', level: 2, boss: false, english: 'choice' },
  { word: 'oplossing', article: 'de', dim: 'oplossinkje', plural: 'oplossingen', level: 2, boss: false, english: 'solution' },
  { word: 'taal', article: 'de', dim: 'taaltje', plural: 'talen', level: 2, boss: false, english: 'language' },
  { word: 'wet', article: 'de', dim: 'wetje', plural: 'wetten', level: 2, boss: false, english: 'law' },
  { word: 'kunst', article: 'de', dim: 'kunstje', plural: 'kunsten', level: 2, boss: false, english: 'art' },
  { word: 'buurt', article: 'de', dim: 'buurtje', plural: 'buurten', level: 2, boss: false, english: 'neighborhood' },
  { word: 'probleem', article: 'het', dim: 'probleempje', plural: 'problemen', level: 2, boss: false, english: 'problem' },
  { word: 'gevoel', article: 'het', dim: 'gevoeltje', plural: 'gevoelens', level: 2, boss: true, english: 'feeling' },
  { word: 'moment', article: 'het', dim: 'momentje', plural: 'momenten', level: 2, boss: false, english: 'moment' },
  { word: 'idee', article: 'het', dim: 'ideetje', plural: "ideeën", level: 2, boss: false, english: 'idea' },
  { word: 'woord', article: 'het', dim: 'woordje', plural: 'woorden', level: 2, boss: false, english: 'word' },
  { word: 'lichaam', article: 'het', dim: 'lichaampje', plural: 'lichamen', level: 2, boss: false, english: 'body' },
  { word: 'voorbeeld', article: 'het', dim: 'voorbeeldje', plural: 'voorbeelden', level: 2, boss: true, english: 'example' },
  { word: 'systeem', article: 'het', dim: 'systeempje', plural: 'systemen', level: 2, boss: false, english: 'system' },
  { word: 'contact', article: 'het', dim: 'contactje', plural: 'contacten', level: 2, boss: false, english: 'contact' },
  { word: 'bericht', article: 'het', dim: 'berichtje', plural: 'berichten', level: 2, boss: false, english: 'message' },
  { word: 'recht', article: 'het', dim: 'rechtje', plural: 'rechten', level: 2, boss: false, english: 'right' },
  { word: 'bedrijf', article: 'het', dim: 'bedrijfje', plural: 'bedrijven', level: 2, boss: false, english: 'company' },
  { word: 'doel', article: 'het', dim: 'doeltje', plural: 'doelen', level: 2, boss: false, english: 'goal' },
  { word: 'plan', article: 'het', dim: 'plannetje', plural: 'plannen', level: 2, boss: false, english: 'plan' },
  { word: 'project', article: 'het', dim: 'projectje', plural: 'projecten', level: 2, boss: false, english: 'project' },

  // B1: Complex and Abstract Vocabulary (15 De, 15 Het)
  { word: 'gedachte', article: 'de', dim: 'gedachtetje', plural: 'gedachten', level: 3, boss: true, english: 'thought' },
  { word: 'betekenis', article: 'de', dim: 'betekenisje', plural: 'betekenissen', level: 3, boss: false, english: 'meaning' },
  { word: 'overheid', article: 'de', dim: 'overheidje', plural: 'overheden', level: 3, boss: true, english: 'government' },
  { word: 'ervaring', article: 'de', dim: 'ervarinkje', plural: 'ervaringen', level: 3, boss: false, english: 'experience' },
  { word: 'toekomst', article: 'de', dim: 'toekomstje', plural: 'toekomsten', level: 3, boss: true, english: 'future' },
  { word: 'beslissing', article: 'de', dim: 'beslissinkje', plural: 'beslissingen', level: 3, boss: false, english: 'decision' },
  { word: 'verandering', article: 'de', dim: 'veranderinkje', plural: 'veranderingen', level: 3, boss: true, english: 'change' },
  { word: 'invloed', article: 'de', dim: 'invloedje', plural: 'invloeden', level: 3, boss: false, english: 'influence' },
  { word: 'maatschappij', article: 'de', dim: 'maatschappijtje', plural: 'maatschappijen', level: 3, boss: true, english: 'society' },
  { word: 'relatie', article: 'de', dim: 'relatietje', plural: 'relaties', level: 3, boss: true, english: 'relationship' },
  { word: 'techniek', article: 'de', dim: 'techniekje', plural: 'technieken', level: 3, boss: false, english: 'technique' },
  { word: 'kwaliteit', article: 'de', dim: 'kwaliteitje', plural: 'kwaliteiten', level: 3, boss: false, english: 'quality' },
  { word: 'veiligheid', article: 'de', dim: 'veiligheidje', plural: 'veiligheden', level: 3, boss: false, english: 'safety' },
  { word: 'ontwikkeling', article: 'de', dim: 'ontwikkelinkje', plural: 'ontwikkelingen', level: 3, boss: false, english: 'development' },
  { word: 'voorwaarde', article: 'de', dim: 'voorwaardetje', plural: 'voorwaarden', level: 3, boss: false, english: 'condition' },
  { word: 'verschil', article: 'het', dim: 'verschilletje', plural: 'verschillen', level: 3, boss: true, english: 'difference' },
  { word: 'gevolg', article: 'het', dim: 'gevolgje', plural: 'gevolgen', level: 3, boss: true, english: 'consequence' },
  { word: 'onderzoek', article: 'het', dim: 'onderzoekje', plural: 'onderzoeken', level: 3, boss: true, english: 'research' },
  { word: 'bewijs', article: 'het', dim: 'bewijsje', plural: 'bewijzen', level: 3, boss: false, english: 'proof' },
  { word: 'netwerk', article: 'het', dim: 'netwerkje', plural: 'netwerken', level: 3, boss: true, english: 'network' },
  { word: 'nadeel', article: 'het', dim: 'nadeeltje', plural: 'nadelen', level: 3, boss: false, english: 'disadvantage' },
  { word: 'voordeel', article: 'het', dim: 'voordeeltje', plural: 'voordelen', level: 3, boss: false, english: 'advantage' },
  { word: 'risico', article: 'het', dim: 'risicootje', plural: "risico's", level: 3, boss: true, english: 'risk' },
  { word: 'oordeel', article: 'het', dim: 'oordeeltje', plural: 'oordelen', level: 3, boss: false, english: 'judgement' },
  { word: 'proces', article: 'het', dim: 'procesje', plural: 'processen', level: 3, boss: true, english: 'process' },
  { word: 'niveau', article: 'het', dim: 'niveautje', plural: 'niveaus', level: 3, boss: false, english: 'level' },
  { word: 'tekort', article: 'het', dim: 'tekortje', plural: 'tekorten', level: 3, boss: false, english: 'shortage' },
  { word: 'verleden', article: 'het', dim: 'verledentje', plural: 'verledens', level: 3, boss: true, english: 'past' },
  { word: 'gedrag', article: 'het', dim: 'gedragje', plural: 'gedragingen', level: 3, boss: false, english: 'behaviour' },
  { word: 'kenmerk', article: 'het', dim: 'kenmerkje', plural: 'kenmerken', level: 3, boss: false, english: 'characteristic' }
];