import { WordData } from './types';

export const COLORS = {
  bg: '#000000',
  white: '#FFFFFF',
  red: '#FF0000',
  redDim: '#880000',
};

/** Labels for each stage, indexed by WordData.level. */
export const LEVEL_LABELS = ['A0', 'A1', 'A2', 'B1'];

/**
 * The word bank. Every level holds exactly 20 de-words and 20 het-words, so the
 * deck (see WordDeck) can deal a true 50/50 split. Boss words are two de and two
 * het per level, chosen because their diminutive and plural are forms people
 * really use: a boss cycles through all three during the fight.
 */
export const WORDS: WordData[] = [
  // A0: first words - people, animals, things at home (20 de, 20 het)
  { word: 'hond', article: 'de', dim: 'hondje', plural: 'honden', level: 0, boss: true, english: 'dog' },
  { word: 'fiets', article: 'de', dim: 'fietsje', plural: 'fietsen', level: 0, boss: true, english: 'bicycle' },
  { word: 'kat', article: 'de', dim: 'katje', plural: 'katten', level: 0, boss: false, english: 'cat' },
  { word: 'man', article: 'de', dim: 'mannetje', plural: 'mannen', level: 0, boss: false, english: 'man' },
  { word: 'vrouw', article: 'de', dim: 'vrouwtje', plural: 'vrouwen', level: 0, boss: false, english: 'woman' },
  { word: 'tafel', article: 'de', dim: 'tafeltje', plural: 'tafels', level: 0, boss: false, english: 'table' },
  { word: 'stoel', article: 'de', dim: 'stoeltje', plural: 'stoelen', level: 0, boss: false, english: 'chair' },
  { word: 'deur', article: 'de', dim: 'deurtje', plural: 'deuren', level: 0, boss: false, english: 'door' },
  { word: 'auto', article: 'de', dim: 'autootje', plural: "auto's", level: 0, boss: false, english: 'car' },
  { word: 'appel', article: 'de', dim: 'appeltje', plural: 'appels', level: 0, boss: false, english: 'apple' },
  { word: 'boom', article: 'de', dim: 'boompje', plural: 'bomen', level: 0, boss: false, english: 'tree' },
  { word: 'jas', article: 'de', dim: 'jasje', plural: 'jassen', level: 0, boss: false, english: 'coat' },
  { word: 'zoon', article: 'de', dim: 'zoontje', plural: 'zonen', level: 0, boss: false, english: 'son' },
  { word: 'dochter', article: 'de', dim: 'dochtertje', plural: 'dochters', level: 0, boss: false, english: 'daughter' },
  { word: 'bal', article: 'de', dim: 'balletje', plural: 'ballen', level: 0, boss: false, english: 'ball' },
  { word: 'kop', article: 'de', dim: 'kopje', plural: 'koppen', level: 0, boss: false, english: 'cup' },
  { word: 'lamp', article: 'de', dim: 'lampje', plural: 'lampen', level: 0, boss: false, english: 'lamp' },
  { word: 'vis', article: 'de', dim: 'visje', plural: 'vissen', level: 0, boss: false, english: 'fish' },
  { word: 'sleutel', article: 'de', dim: 'sleuteltje', plural: 'sleutels', level: 0, boss: false, english: 'key' },
  { word: 'tas', article: 'de', dim: 'tasje', plural: 'tassen', level: 0, boss: false, english: 'bag' },
  { word: 'huis', article: 'het', dim: 'huisje', plural: 'huizen', level: 0, boss: true, english: 'house' },
  { word: 'kind', article: 'het', dim: 'kindje', plural: 'kinderen', level: 0, boss: true, english: 'child' },
  { word: 'boek', article: 'het', dim: 'boekje', plural: 'boeken', level: 0, boss: false, english: 'book' },
  { word: 'raam', article: 'het', dim: 'raampje', plural: 'ramen', level: 0, boss: false, english: 'window' },
  { word: 'bed', article: 'het', dim: 'bedje', plural: 'bedden', level: 0, boss: false, english: 'bed' },
  { word: 'brood', article: 'het', dim: 'broodje', plural: 'broden', level: 0, boss: false, english: 'bread' },
  { word: 'glas', article: 'het', dim: 'glaasje', plural: 'glazen', level: 0, boss: false, english: 'glass' },
  { word: 'meisje', article: 'het', dim: 'meisje', plural: 'meisjes', level: 0, boss: false, english: 'girl' },
  { word: 'paard', article: 'het', dim: 'paardje', plural: 'paarden', level: 0, boss: false, english: 'horse' },
  { word: 'ei', article: 'het', dim: 'eitje', plural: 'eieren', level: 0, boss: false, english: 'egg' },
  { word: 'dier', article: 'het', dim: 'diertje', plural: 'dieren', level: 0, boss: false, english: 'animal' },
  { word: 'schaap', article: 'het', dim: 'schaapje', plural: 'schapen', level: 0, boss: false, english: 'sheep' },
  { word: 'varken', article: 'het', dim: 'varkentje', plural: 'varkens', level: 0, boss: false, english: 'pig' },
  { word: 'bord', article: 'het', dim: 'bordje', plural: 'borden', level: 0, boss: false, english: 'plate' },
  { word: 'mes', article: 'het', dim: 'mesje', plural: 'messen', level: 0, boss: false, english: 'knife' },
  { word: 'konijn', article: 'het', dim: 'konijntje', plural: 'konijnen', level: 0, boss: false, english: 'rabbit' },
  { word: 'hoofd', article: 'het', dim: 'hoofdje', plural: 'hoofden', level: 0, boss: false, english: 'head' },
  { word: 'oor', article: 'het', dim: 'oortje', plural: 'oren', level: 0, boss: false, english: 'ear' },
  { word: 'been', article: 'het', dim: 'beentje', plural: 'benen', level: 0, boss: false, english: 'leg' },
  { word: 'potlood', article: 'het', dim: 'potloodje', plural: 'potloden', level: 0, boss: false, english: 'pencil' },

  // A1: daily life - town, time, travel, body (20 de, 20 het)
  { word: 'stad', article: 'de', dim: 'stadje', plural: 'steden', level: 1, boss: true, english: 'city' },
  { word: 'trein', article: 'de', dim: 'treintje', plural: 'treinen', level: 1, boss: true, english: 'train' },
  { word: 'school', article: 'de', dim: 'schooltje', plural: 'scholen', level: 1, boss: false, english: 'school' },
  { word: 'dag', article: 'de', dim: 'dagje', plural: 'dagen', level: 1, boss: false, english: 'day' },
  { word: 'week', article: 'de', dim: 'weekje', plural: 'weken', level: 1, boss: false, english: 'week' },
  { word: 'maand', article: 'de', dim: 'maandje', plural: 'maanden', level: 1, boss: false, english: 'month' },
  { word: 'straat', article: 'de', dim: 'straatje', plural: 'straten', level: 1, boss: false, english: 'street' },
  { word: 'bus', article: 'de', dim: 'busje', plural: 'bussen', level: 1, boss: false, english: 'bus' },
  { word: 'winkel', article: 'de', dim: 'winkeltje', plural: 'winkels', level: 1, boss: false, english: 'shop' },
  { word: 'kamer', article: 'de', dim: 'kamertje', plural: 'kamers', level: 1, boss: false, english: 'room' },
  { word: 'keuken', article: 'de', dim: 'keukentje', plural: 'keukens', level: 1, boss: false, english: 'kitchen' },
  { word: 'vriend', article: 'de', dim: 'vriendje', plural: 'vrienden', level: 1, boss: false, english: 'friend' },
  { word: 'vraag', article: 'de', dim: 'vraagje', plural: 'vragen', level: 1, boss: false, english: 'question' },
  { word: 'naam', article: 'de', dim: 'naampje', plural: 'namen', level: 1, boss: false, english: 'name' },
  { word: 'hand', article: 'de', dim: 'handje', plural: 'handen', level: 1, boss: false, english: 'hand' },
  { word: 'voet', article: 'de', dim: 'voetje', plural: 'voeten', level: 1, boss: false, english: 'foot' },
  { word: 'vogel', article: 'de', dim: 'vogeltje', plural: 'vogels', level: 1, boss: false, english: 'bird' },
  { word: 'weg', article: 'de', dim: 'weggetje', plural: 'wegen', level: 1, boss: false, english: 'road' },
  { word: 'fles', article: 'de', dim: 'flesje', plural: 'flessen', level: 1, boss: false, english: 'bottle' },
  { word: 'telefoon', article: 'de', dim: 'telefoontje', plural: 'telefoons', level: 1, boss: false, english: 'phone' },
  { word: 'jaar', article: 'het', dim: 'jaartje', plural: 'jaren', level: 1, boss: true, english: 'year' },
  { word: 'station', article: 'het', dim: 'stationnetje', plural: 'stations', level: 1, boss: true, english: 'station' },
  { word: 'land', article: 'het', dim: 'landje', plural: 'landen', level: 1, boss: false, english: 'country' },
  { word: 'oog', article: 'het', dim: 'oogje', plural: 'ogen', level: 1, boss: false, english: 'eye' },
  { word: 'vliegtuig', article: 'het', dim: 'vliegtuigje', plural: 'vliegtuigen', level: 1, boss: false, english: 'airplane' },
  { word: 'ziekenhuis', article: 'het', dim: 'ziekenhuisje', plural: 'ziekenhuizen', level: 1, boss: false, english: 'hospital' },
  { word: 'restaurant', article: 'het', dim: 'restaurantje', plural: 'restaurants', level: 1, boss: false, english: 'restaurant' },
  { word: 'strand', article: 'het', dim: 'strandje', plural: 'stranden', level: 1, boss: false, english: 'beach' },
  { word: 'bos', article: 'het', dim: 'bosje', plural: 'bossen', level: 1, boss: false, english: 'forest' },
  { word: 'feest', article: 'het', dim: 'feestje', plural: 'feesten', level: 1, boss: false, english: 'party' },
  { word: 'antwoord', article: 'het', dim: 'antwoordje', plural: 'antwoorden', level: 1, boss: false, english: 'answer' },
  { word: 'adres', article: 'het', dim: 'adresje', plural: 'adressen', level: 1, boss: false, english: 'address' },
  { word: 'café', article: 'het', dim: 'cafeetje', plural: 'cafés', level: 1, boss: false, english: 'café' },
  { word: 'dorp', article: 'het', dim: 'dorpje', plural: 'dorpen', level: 1, boss: false, english: 'village' },
  { word: 'plein', article: 'het', dim: 'pleintje', plural: 'pleinen', level: 1, boss: false, english: 'square' },
  { word: 'kantoor', article: 'het', dim: 'kantoortje', plural: 'kantoren', level: 1, boss: false, english: 'office' },
  { word: 'uur', article: 'het', dim: 'uurtje', plural: 'uren', level: 1, boss: false, english: 'hour' },
  { word: 'weekend', article: 'het', dim: 'weekendje', plural: 'weekenden', level: 1, boss: false, english: 'weekend' },
  { word: 'gezicht', article: 'het', dim: 'gezichtje', plural: 'gezichten', level: 1, boss: false, english: 'face' },
  { word: 'nummer', article: 'het', dim: 'nummertje', plural: 'nummers', level: 1, boss: false, english: 'number' },

  // A2: social life - plans, work, feelings, errands (20 de, 20 het)
  { word: 'reis', article: 'de', dim: 'reisje', plural: 'reizen', level: 2, boss: true, english: 'trip' },
  { word: 'afspraak', article: 'de', dim: 'afspraakje', plural: 'afspraken', level: 2, boss: true, english: 'appointment' },
  { word: 'kans', article: 'de', dim: 'kansje', plural: 'kansen', level: 2, boss: false, english: 'chance' },
  { word: 'manier', article: 'de', dim: 'maniertje', plural: 'manieren', level: 2, boss: false, english: 'way' },
  { word: 'wereld', article: 'de', dim: 'wereldje', plural: 'werelden', level: 2, boss: false, english: 'world' },
  { word: 'markt', article: 'de', dim: 'marktje', plural: 'markten', level: 2, boss: false, english: 'market' },
  { word: 'prijs', article: 'de', dim: 'prijsje', plural: 'prijzen', level: 2, boss: false, english: 'price' },
  { word: 'groep', article: 'de', dim: 'groepje', plural: 'groepen', level: 2, boss: false, english: 'group' },
  { word: 'taal', article: 'de', dim: 'taaltje', plural: 'talen', level: 2, boss: false, english: 'language' },
  { word: 'buurt', article: 'de', dim: 'buurtje', plural: 'buurten', level: 2, boss: false, english: 'neighbourhood' },
  { word: 'vakantie', article: 'de', dim: 'vakantietje', plural: 'vakanties', level: 2, boss: false, english: 'holiday' },
  { word: 'baan', article: 'de', dim: 'baantje', plural: 'banen', level: 2, boss: false, english: 'job' },
  { word: 'les', article: 'de', dim: 'lesje', plural: 'lessen', level: 2, boss: false, english: 'lesson' },
  { word: 'brief', article: 'de', dim: 'briefje', plural: 'brieven', level: 2, boss: false, english: 'letter' },
  { word: 'kaart', article: 'de', dim: 'kaartje', plural: 'kaarten', level: 2, boss: false, english: 'card' },
  { word: 'zin', article: 'de', dim: 'zinnetje', plural: 'zinnen', level: 2, boss: false, english: 'sentence' },
  { word: 'fout', article: 'de', dim: 'foutje', plural: 'fouten', level: 2, boss: false, english: 'mistake' },
  { word: 'plek', article: 'de', dim: 'plekje', plural: 'plekken', level: 2, boss: false, english: 'spot' },
  { word: 'hoek', article: 'de', dim: 'hoekje', plural: 'hoeken', level: 2, boss: false, english: 'corner' },
  { word: 'kleur', article: 'de', dim: 'kleurtje', plural: 'kleuren', level: 2, boss: false, english: 'colour' },
  { word: 'verhaal', article: 'het', dim: 'verhaaltje', plural: 'verhalen', level: 2, boss: true, english: 'story' },
  { word: 'probleem', article: 'het', dim: 'probleempje', plural: 'problemen', level: 2, boss: true, english: 'problem' },
  { word: 'gevoel', article: 'het', dim: 'gevoeltje', plural: 'gevoelens', level: 2, boss: false, english: 'feeling' },
  { word: 'moment', article: 'het', dim: 'momentje', plural: 'momenten', level: 2, boss: false, english: 'moment' },
  { word: 'idee', article: 'het', dim: 'ideetje', plural: 'ideeën', level: 2, boss: false, english: 'idea' },
  { word: 'woord', article: 'het', dim: 'woordje', plural: 'woorden', level: 2, boss: false, english: 'word' },
  { word: 'voorbeeld', article: 'het', dim: 'voorbeeldje', plural: 'voorbeelden', level: 2, boss: false, english: 'example' },
  { word: 'bericht', article: 'het', dim: 'berichtje', plural: 'berichten', level: 2, boss: false, english: 'message' },
  { word: 'bedrijf', article: 'het', dim: 'bedrijfje', plural: 'bedrijven', level: 2, boss: false, english: 'company' },
  { word: 'doel', article: 'het', dim: 'doeltje', plural: 'doelen', level: 2, boss: false, english: 'goal' },
  { word: 'plan', article: 'het', dim: 'plannetje', plural: 'plannen', level: 2, boss: false, english: 'plan' },
  { word: 'gesprek', article: 'het', dim: 'gesprekje', plural: 'gesprekken', level: 2, boss: false, english: 'conversation' },
  { word: 'cadeau', article: 'het', dim: 'cadeautje', plural: 'cadeaus', level: 2, boss: false, english: 'gift' },
  { word: 'geheim', article: 'het', dim: 'geheimpje', plural: 'geheimen', level: 2, boss: false, english: 'secret' },
  { word: 'lied', article: 'het', dim: 'liedje', plural: 'liederen', level: 2, boss: false, english: 'song' },
  { word: 'spel', article: 'het', dim: 'spelletje', plural: 'spellen', level: 2, boss: false, english: 'game' },
  { word: 'museum', article: 'het', dim: 'museumpje', plural: 'musea', level: 2, boss: false, english: 'museum' },
  { word: 'pakket', article: 'het', dim: 'pakketje', plural: 'pakketten', level: 2, boss: false, english: 'parcel' },
  { word: 'gebouw', article: 'het', dim: 'gebouwtje', plural: 'gebouwen', level: 2, boss: false, english: 'building' },
  { word: 'formulier', article: 'het', dim: 'formuliertje', plural: 'formulieren', level: 2, boss: false, english: 'form' },

  // B1: abstract ideas - society, reasoning, change (20 de, 20 het)
  { word: 'relatie', article: 'de', dim: 'relatietje', plural: 'relaties', level: 3, boss: true, english: 'relationship' },
  { word: 'discussie', article: 'de', dim: 'discussietje', plural: 'discussies', level: 3, boss: true, english: 'discussion' },
  { word: 'gedachte', article: 'de', dim: 'gedachtetje', plural: 'gedachten', level: 3, boss: false, english: 'thought' },
  { word: 'betekenis', article: 'de', dim: 'betekenisje', plural: 'betekenissen', level: 3, boss: false, english: 'meaning' },
  { word: 'overheid', article: 'de', dim: 'overheidje', plural: 'overheden', level: 3, boss: false, english: 'government' },
  { word: 'ervaring', article: 'de', dim: 'ervarinkje', plural: 'ervaringen', level: 3, boss: false, english: 'experience' },
  { word: 'toekomst', article: 'de', dim: 'toekomstje', plural: 'toekomsten', level: 3, boss: false, english: 'future' },
  { word: 'beslissing', article: 'de', dim: 'beslissinkje', plural: 'beslissingen', level: 3, boss: false, english: 'decision' },
  { word: 'verandering', article: 'de', dim: 'veranderinkje', plural: 'veranderingen', level: 3, boss: false, english: 'change' },
  { word: 'invloed', article: 'de', dim: 'invloedje', plural: 'invloeden', level: 3, boss: false, english: 'influence' },
  { word: 'maatschappij', article: 'de', dim: 'maatschappijtje', plural: 'maatschappijen', level: 3, boss: false, english: 'society' },
  { word: 'techniek', article: 'de', dim: 'techniekje', plural: 'technieken', level: 3, boss: false, english: 'technique' },
  { word: 'kwaliteit', article: 'de', dim: 'kwaliteitje', plural: 'kwaliteiten', level: 3, boss: false, english: 'quality' },
  { word: 'veiligheid', article: 'de', dim: 'veiligheidje', plural: 'veiligheden', level: 3, boss: false, english: 'safety' },
  { word: 'ontwikkeling', article: 'de', dim: 'ontwikkelinkje', plural: 'ontwikkelingen', level: 3, boss: false, english: 'development' },
  { word: 'voorwaarde', article: 'de', dim: 'voorwaardetje', plural: 'voorwaarden', level: 3, boss: false, english: 'condition' },
  { word: 'gewoonte', article: 'de', dim: 'gewoontetje', plural: 'gewoontes', level: 3, boss: false, english: 'habit' },
  { word: 'mening', article: 'de', dim: 'meninkje', plural: 'meningen', level: 3, boss: false, english: 'opinion' },
  { word: 'omgeving', article: 'de', dim: 'omgevinkje', plural: 'omgevingen', level: 3, boss: false, english: 'surroundings' },
  { word: 'verantwoordelijkheid', article: 'de', dim: 'verantwoordelijkheidje', plural: 'verantwoordelijkheden', level: 3, boss: false, english: 'responsibility' },
  { word: 'verschil', article: 'het', dim: 'verschilletje', plural: 'verschillen', level: 3, boss: true, english: 'difference' },
  { word: 'voordeel', article: 'het', dim: 'voordeeltje', plural: 'voordelen', level: 3, boss: true, english: 'advantage' },
  { word: 'gevolg', article: 'het', dim: 'gevolgje', plural: 'gevolgen', level: 3, boss: false, english: 'consequence' },
  { word: 'onderzoek', article: 'het', dim: 'onderzoekje', plural: 'onderzoeken', level: 3, boss: false, english: 'research' },
  { word: 'bewijs', article: 'het', dim: 'bewijsje', plural: 'bewijzen', level: 3, boss: false, english: 'proof' },
  { word: 'netwerk', article: 'het', dim: 'netwerkje', plural: 'netwerken', level: 3, boss: false, english: 'network' },
  { word: 'nadeel', article: 'het', dim: 'nadeeltje', plural: 'nadelen', level: 3, boss: false, english: 'disadvantage' },
  { word: 'risico', article: 'het', dim: 'risicootje', plural: "risico's", level: 3, boss: false, english: 'risk' },
  { word: 'oordeel', article: 'het', dim: 'oordeeltje', plural: 'oordelen', level: 3, boss: false, english: 'judgement' },
  { word: 'proces', article: 'het', dim: 'procesje', plural: 'processen', level: 3, boss: false, english: 'process' },
  { word: 'niveau', article: 'het', dim: 'niveautje', plural: 'niveaus', level: 3, boss: false, english: 'level' },
  { word: 'tekort', article: 'het', dim: 'tekortje', plural: 'tekorten', level: 3, boss: false, english: 'shortage' },
  { word: 'verleden', article: 'het', dim: 'verledentje', plural: 'verledens', level: 3, boss: false, english: 'past' },
  { word: 'gedrag', article: 'het', dim: 'gedragje', plural: 'gedragingen', level: 3, boss: false, english: 'behaviour' },
  { word: 'kenmerk', article: 'het', dim: 'kenmerkje', plural: 'kenmerken', level: 3, boss: false, english: 'characteristic' },
  { word: 'resultaat', article: 'het', dim: 'resultaatje', plural: 'resultaten', level: 3, boss: false, english: 'result' },
  { word: 'belang', article: 'het', dim: 'belangetje', plural: 'belangen', level: 3, boss: false, english: 'interest' },
  { word: 'gebied', article: 'het', dim: 'gebiedje', plural: 'gebieden', level: 3, boss: false, english: 'area' },
  { word: 'onderwerp', article: 'het', dim: 'onderwerpje', plural: 'onderwerpen', level: 3, boss: false, english: 'topic' },
  { word: 'standpunt', article: 'het', dim: 'standpuntje', plural: 'standpunten', level: 3, boss: false, english: 'point of view' },
];
